(function (angular) {
    angular.module('treinadorPokemon')
        .service('pokemonService', pokemonService);

    function pokemonService() {
        this.getTipos = function () {
            return [
                'Normal',
                'Lutador',
                'Voador',
                'Venenoso',
                'Terrestre',
                'Pedra',
                'Inseto',
                'Fantasma',
                'Fogo',
                'Agua',
                'Eletrico',
                'Psiquico',
                'Gelo',
                'Dragao',
                'Fada'
            ];
        };

        this.getPokemons = function () {
            var obj = [{
                "icone": "./spas/resources/icones/1.png",
                "nome": "Bulbasaur",
                "tipos": [{
                    "nome": "venenoso",
                    "id": "1"
                }, {
                    "nome": "grama",
                    "id": "2"
                }],
                "level": 5,
                "id": 0,
                "ataque": 13,
                "defesa": 13,
                "vida": 68
            }, {
                "icone": "./spas/resources/icones/2.png",
                "nome": "Ivysaur",
                "tipos": [{
                    "nome": "venenoso",
                    "id": "1"
                }, {
                    "nome": "grama",
                    "id": "2"
                }],
                "level": 5,
                "id": 1,
                "ataque": 5,
                "defesa": 1,
                "vida": 52
            }, {
                "icone": "./spas/resources/icones/3.png",
                "nome": "Venusaur",
                "tipos": [{
                    "nome": "venenoso",
                    "id": "1"
                }, {
                    "nome": "grama",
                    "id": "2"
                }],
                "level": 5,
                "id": 2,
                "ataque": 8,
                "defesa": 18,
                "vida": 37
            }, {
                "icone": "./spas/resources/icones/4.png",
                "nome": "Charmander",
                "tipos": [{
                    "nome": "fogo",
                    "id": "1"
                }],
                "level": 5,
                "id": 3,
                "ataque": 18,
                "defesa": 15,
                "vida": 61
            }, {
                "icone": "./spas/resources/icones/5.png",
                "nome": "Charmeleon",
                "tipos": [{
                    "nome": "fogo",
                    "id": "1"
                }],
                "level": 5,
                "id": 4,
                "ataque": 12,
                "defesa": 3,
                "vida": 84
            }, {
                "icone": "./spas/resources/icones/6.png",
                "nome": "Charizard",
                "tipos": [{
                    "nome": "voador",
                    "id": "1"
                }, {
                    "nome": "fogo",
                    "id": "2"
                }],
                "level": 5,
                "id": 5,
                "ataque": 8,
                "defesa": 16,
                "vida": 67
            }, {
                "icone": "./spas/resources/icones/7.png",
                "nome": "Squirtle",
                "tipos": [{
                    "nome": "agua",
                    "id": "1"
                }],
                "level": 5,
                "id": 6,
                "ataque": 4,
                "defesa": 15,
                "vida": 62
            }, {
                "icone": "./spas/resources/icones/8.png",
                "nome": "Wartortle",
                "tipos": [{
                    "nome": "agua",
                    "id": "1"
                }],
                "level": 5,
                "id": 7,
                "ataque": 9,
                "defesa": 1,
                "vida": 50
            }, {
                "icone": "./spas/resources/icones/9.png",
                "nome": "Blastoise",
                "tipos": [{
                    "nome": "agua",
                    "id": "1"
                }],
                "level": 5,
                "id": 8,
                "ataque": 4,
                "defesa": 5,
                "vida": 63
            }, {
                "icone": "./spas/resources/icones/10.png",
                "nome": "Caterpie",
                "tipos": [{
                    "nome": "inseto",
                    "id": "1"
                }],
                "level": 5,
                "id": 9,
                "ataque": 10,
                "defesa": 16,
                "vida": 49
            }, {
                "icone": "./spas/resources/icones/11.png",
                "nome": "Metapod",
                "tipos": [{
                    "nome": "inseto",
                    "id": "1"
                }],
                "level": 5,
                "id": 10,
                "ataque": 19,
                "defesa": 15,
                "vida": 57
            }, {
                "icone": "./spas/resources/icones/12.png",
                "nome": "Butterfree",
                "tipos": [{
                    "nome": "voador",
                    "id": "1"
                }, {
                    "nome": "inseto",
                    "id": "2"
                }],
                "level": 5,
                "id": 11,
                "ataque": 14,
                "defesa": 10,
                "vida": 83
            }, {
                "icone": "./spas/resources/icones/13.png",
                "nome": "Weedle",
                "tipos": [{
                    "nome": "venenoso",
                    "id": "1"
                }, {
                    "nome": "inseto",
                    "id": "2"
                }],
                "level": 5,
                "id": 12,
                "ataque": 13,
                "defesa": 10,
                "vida": 34
            }, {
                "icone": "./spas/resources/icones/14.png",
                "nome": "Kakuna",
                "tipos": [{
                    "nome": "venenoso",
                    "id": "1"
                }, {
                    "nome": "inseto",
                    "id": "2"
                }],
                "level": 5,
                "id": 13,
                "ataque": 10,
                "defesa": 5,
                "vida": 60
            }, {
                "icone": "./spas/resources/icones/15.png",
                "nome": "Beedrill",
                "tipos": [{
                    "nome": "venenoso",
                    "id": "1"
                }, {
                    "nome": "inseto",
                    "id": "2"
                }],
                "level": 5,
                "id": 14,
                "ataque": 2,
                "defesa": 10,
                "vida": 48
            }, {
                "icone": "./spas/resources/icones/16.png",
                "nome": "Pidgey",
                "tipos": [{
                    "nome": "normal",
                    "id": "1"
                }, {
                    "nome": "voador",
                    "id": "2"
                }],
                "level": 5,
                "id": 15,
                "ataque": 7,
                "defesa": 16,
                "vida": 43
            }, {
                "icone": "./spas/resources/icones/17.png",
                "nome": "Pidgeotto",
                "tipos": [{
                    "nome": "normal",
                    "id": "1"
                }, {
                    "nome": "voador",
                    "id": "2"
                }],
                "level": 5,
                "id": 16,
                "ataque": 5,
                "defesa": 8,
                "vida": 99
            }, {
                "icone": "./spas/resources/icones/18.png",
                "nome": "Pidgeot",
                "tipos": [{
                    "nome": "normal",
                    "id": "1"
                }, {
                    "nome": "voador",
                    "id": "2"
                }],
                "level": 5,
                "id": 17,
                "ataque": 10,
                "defesa": 11,
                "vida": 70
            }, {
                "icone": "./spas/resources/icones/19.png",
                "nome": "Rattata",
                "tipos": [{
                    "nome": "normal",
                    "id": "1"
                }],
                "level": 5,
                "id": 18,
                "ataque": 17,
                "defesa": 7,
                "vida": 56
            }, {
                "icone": "./spas/resources/icones/20.png",
                "nome": "Raticate",
                "tipos": [{
                    "nome": "normal",
                    "id": "1"
                }],
                "level": 5,
                "id": 19,
                "ataque": 17,
                "defesa": 4,
                "vida": 92
            }, {
                "icone": "./spas/resources/icones/21.png",
                "nome": "Spearow",
                "tipos": [{
                    "nome": "normal",
                    "id": "1"
                }, {
                    "nome": "voador",
                    "id": "2"
                }],
                "level": 5,
                "id": 20,
                "ataque": 12,
                "defesa": 7,
                "vida": 42
            }, {
                "icone": "./spas/resources/icones/22.png",
                "nome": "Fearow",
                "tipos": [{
                    "nome": "normal",
                    "id": "1"
                }, {
                    "nome": "voador",
                    "id": "2"
                }],
                "level": 5,
                "id": 21,
                "ataque": 7,
                "defesa": 6,
                "vida": 46
            }, {
                "icone": "./spas/resources/icones/23.png",
                "nome": "Ekans",
                "tipos": [{
                    "nome": "venenoso",
                    "id": "1"
                }],
                "level": 5,
                "id": 22,
                "ataque": 7,
                "defesa": 6,
                "vida": 32
            }, {
                "icone": "./spas/resources/icones/24.png",
                "nome": "Arbok",
                "tipos": [{
                    "nome": "venenoso",
                    "id": "1"
                }],
                "level": 5,
                "id": 23,
                "ataque": 15,
                "defesa": 3,
                "vida": 88
            }, {
                "icone": "./spas/resources/icones/25.png",
                "nome": "Pikachu",
                "tipos": [{
                    "nome": "eletrico",
                    "id": "1"
                }],
                "level": 5,
                "id": 24,
                "ataque": 7,
                "defesa": 19,
                "vida": 27
            }, {
                "icone": "./spas/resources/icones/26.png",
                "nome": "Raichu",
                "tipos": [{
                    "nome": "eletrico",
                    "id": "1"
                }],
                "level": 5,
                "id": 25,
                "ataque": 12,
                "defesa": 14,
                "vida": 48
            }, {
                "icone": "./spas/resources/icones/27.png",
                "nome": "Sandshrew",
                "tipos": [{
                    "nome": "terrestre",
                    "id": "1"
                }],
                "level": 5,
                "id": 26,
                "ataque": 17,
                "defesa": 16,
                "vida": 77
            }, {
                "icone": "./spas/resources/icones/28.png",
                "nome": "Sandslash",
                "tipos": [{
                    "nome": "terrestre",
                    "id": "1"
                }],
                "level": 5,
                "id": 27,
                "ataque": 10,
                "defesa": 2,
                "vida": 68
            }, {
                "icone": "./spas/resources/icones/29.png",
                "nome": "Nidoran-f",
                "tipos": [{
                    "nome": "venenoso",
                    "id": "1"
                }],
                "level": 5,
                "id": 28,
                "ataque": 10,
                "defesa": 14,
                "vida": 83
            }, {
                "icone": "./spas/resources/icones/30.png",
                "nome": "Nidorina",
                "tipos": [{
                    "nome": "venenoso",
                    "id": "1"
                }],
                "level": 5,
                "id": 29,
                "ataque": 6,
                "defesa": 10,
                "vida": 53
            }, {
                "icone": "./spas/resources/icones/31.png",
                "nome": "Nidoqueen",
                "tipos": [{
                    "nome": "venenoso",
                    "id": "1"
                }, {
                    "nome": "terrestre",
                    "id": "2"
                }],
                "level": 5,
                "id": 30,
                "ataque": 13,
                "defesa": 4,
                "vida": 96
            }, {
                "icone": "./spas/resources/icones/32.png",
                "nome": "Nidoran-m",
                "tipos": [{
                    "nome": "venenoso",
                    "id": "1"
                }],
                "level": 5,
                "id": 31,
                "ataque": 5,
                "defesa": 5,
                "vida": 93
            }, {
                "icone": "./spas/resources/icones/33.png",
                "nome": "Nidorino",
                "tipos": [{
                    "nome": "venenoso",
                    "id": "1"
                }],
                "level": 5,
                "id": 32,
                "ataque": 14,
                "defesa": 13,
                "vida": 81
            }, {
                "icone": "./spas/resources/icones/34.png",
                "nome": "Nidoking",
                "tipos": [{
                    "nome": "venenoso",
                    "id": "1"
                }, {
                    "nome": "terrestre",
                    "id": "2"
                }],
                "level": 5,
                "id": 33,
                "ataque": 6,
                "defesa": 16,
                "vida": 67
            }, {
                "icone": "./spas/resources/icones/35.png",
                "nome": "Clefairy",
                "tipos": [{
                    "nome": "fada",
                    "id": "1"
                }],
                "level": 5,
                "id": 34,
                "ataque": 18,
                "defesa": 6,
                "vida": 39
            }, {
                "icone": "./spas/resources/icones/36.png",
                "nome": "Clefable",
                "tipos": [{
                    "nome": "fada",
                    "id": "1"
                }],
                "level": 5,
                "id": 35,
                "ataque": 1,
                "defesa": 8,
                "vida": 66
            }, {
                "icone": "./spas/resources/icones/37.png",
                "nome": "Vulpix",
                "tipos": [{
                    "nome": "fogo",
                    "id": "1"
                }],
                "level": 5,
                "id": 36,
                "ataque": 12,
                "defesa": 17,
                "vida": 90
            }, {
                "icone": "./spas/resources/icones/38.png",
                "nome": "Ninetales",
                "tipos": [{
                    "nome": "fogo",
                    "id": "1"
                }],
                "level": 5,
                "id": 37,
                "ataque": 9,
                "defesa": 11,
                "vida": 54
            }, {
                "icone": "./spas/resources/icones/39.png",
                "nome": "Jigglypuff",
                "tipos": [{
                    "nome": "normal",
                    "id": "1"
                }, {
                    "nome": "fada",
                    "id": "2"
                }],
                "level": 5,
                "id": 38,
                "ataque": 1,
                "defesa": 17,
                "vida": 58
            }, {
                "icone": "./spas/resources/icones/40.png",
                "nome": "Wigglytuff",
                "tipos": [{
                    "nome": "normal",
                    "id": "1"
                }, {
                    "nome": "fada",
                    "id": "2"
                }],
                "level": 5,
                "id": 39,
                "ataque": 10,
                "defesa": 3,
                "vida": 52
            }, {
                "icone": "./spas/resources/icones/41.png",
                "nome": "Zubat",
                "tipos": [{
                    "nome": "voador",
                    "id": "1"
                }, {
                    "nome": "venenoso",
                    "id": "2"
                }],
                "level": 5,
                "id": 40,
                "ataque": 3,
                "defesa": 7,
                "vida": 33
            }, {
                "icone": "./spas/resources/icones/42.png",
                "nome": "Golbat",
                "tipos": [{
                    "nome": "voador",
                    "id": "1"
                }, {
                    "nome": "venenoso",
                    "id": "2"
                }],
                "level": 5,
                "id": 41,
                "ataque": 14,
                "defesa": 17,
                "vida": 38
            }, {
                "icone": "./spas/resources/icones/43.png",
                "nome": "Oddish",
                "tipos": [{
                    "nome": "venenoso",
                    "id": "1"
                }, {
                    "nome": "grama",
                    "id": "2"
                }],
                "level": 5,
                "id": 42,
                "ataque": 8,
                "defesa": 1,
                "vida": 82
            }, {
                "icone": "./spas/resources/icones/44.png",
                "nome": "Gloom",
                "tipos": [{
                    "nome": "venenoso",
                    "id": "1"
                }, {
                    "nome": "grama",
                    "id": "2"
                }],
                "level": 5,
                "id": 43,
                "ataque": 11,
                "defesa": 10,
                "vida": 71
            }, {
                "icone": "./spas/resources/icones/45.png",
                "nome": "Vileplume",
                "tipos": [{
                    "nome": "venenoso",
                    "id": "1"
                }, {
                    "nome": "grama",
                    "id": "2"
                }],
                "level": 5,
                "id": 44,
                "ataque": 10,
                "defesa": 12,
                "vida": 25
            }, {
                "icone": "./spas/resources/icones/46.png",
                "nome": "Paras",
                "tipos": [{
                    "nome": "inseto",
                    "id": "1"
                }, {
                    "nome": "grama",
                    "id": "2"
                }],
                "level": 5,
                "id": 45,
                "ataque": 9,
                "defesa": 11,
                "vida": 49
            }, {
                "icone": "./spas/resources/icones/47.png",
                "nome": "Parasect",
                "tipos": [{
                    "nome": "inseto",
                    "id": "1"
                }, {
                    "nome": "grama",
                    "id": "2"
                }],
                "level": 5,
                "id": 46,
                "ataque": 2,
                "defesa": 14,
                "vida": 67
            }, {
                "icone": "./spas/resources/icones/48.png",
                "nome": "Venonat",
                "tipos": [{
                    "nome": "venenoso",
                    "id": "1"
                }, {
                    "nome": "inseto",
                    "id": "2"
                }],
                "level": 5,
                "id": 47,
                "ataque": 4,
                "defesa": 4,
                "vida": 20
            }, {
                "icone": "./spas/resources/icones/49.png",
                "nome": "Venomoth",
                "tipos": [{
                    "nome": "venenoso",
                    "id": "1"
                }, {
                    "nome": "inseto",
                    "id": "2"
                }],
                "level": 5,
                "id": 48,
                "ataque": 18,
                "defesa": 6,
                "vida": 55
            }, {
                "icone": "./spas/resources/icones/50.png",
                "nome": "Diglett",
                "tipos": [{
                    "nome": "terrestre",
                    "id": "1"
                }],
                "level": 5,
                "id": 49,
                "ataque": 10,
                "defesa": 13,
                "vida": 96
            }, {
                "icone": "./spas/resources/icones/51.png",
                "nome": "Dugtrio",
                "tipos": [{
                    "nome": "terrestre",
                    "id": "1"
                }],
                "level": 5,
                "id": 50,
                "ataque": 4,
                "defesa": 10,
                "vida": 23
            }, {
                "icone": "./spas/resources/icones/52.png",
                "nome": "Meowth",
                "tipos": [{
                    "nome": "normal",
                    "id": "1"
                }],
                "level": 5,
                "id": 51,
                "ataque": 14,
                "defesa": 3,
                "vida": 38
            }, {
                "icone": "./spas/resources/icones/53.png",
                "nome": "Persian",
                "tipos": [{
                    "nome": "normal",
                    "id": "1"
                }],
                "level": 5,
                "id": 52,
                "ataque": 6,
                "defesa": 17,
                "vida": 83
            }, {
                "icone": "./spas/resources/icones/54.png",
                "nome": "Psyduck",
                "tipos": [{
                    "nome": "agua",
                    "id": "1"
                }],
                "level": 5,
                "id": 53,
                "ataque": 11,
                "defesa": 17,
                "vida": 81
            }, {
                "icone": "./spas/resources/icones/55.png",
                "nome": "Golduck",
                "tipos": [{
                    "nome": "agua",
                    "id": "1"
                }],
                "level": 5,
                "id": 54,
                "ataque": 2,
                "defesa": 15,
                "vida": 82
            }, {
                "icone": "./spas/resources/icones/56.png",
                "nome": "Mankey",
                "tipos": [{
                    "nome": "lutador",
                    "id": "1"
                }],
                "level": 5,
                "id": 55,
                "ataque": 13,
                "defesa": 3,
                "vida": 25
            }, {
                "icone": "./spas/resources/icones/57.png",
                "nome": "Primeape",
                "tipos": [{
                    "nome": "lutador",
                    "id": "1"
                }],
                "level": 5,
                "id": 56,
                "ataque": 3,
                "defesa": 15,
                "vida": 68
            }, {
                "icone": "./spas/resources/icones/58.png",
                "nome": "Growlithe",
                "tipos": [{
                    "nome": "fogo",
                    "id": "1"
                }],
                "level": 5,
                "id": 57,
                "ataque": 9,
                "defesa": 13,
                "vida": 60
            }, {
                "icone": "./spas/resources/icones/59.png",
                "nome": "Arcanine",
                "tipos": [{
                    "nome": "fogo",
                    "id": "1"
                }],
                "level": 5,
                "id": 58,
                "ataque": 17,
                "defesa": 11,
                "vida": 83
            }, {
                "icone": "./spas/resources/icones/60.png",
                "nome": "Poliwag",
                "tipos": [{
                    "nome": "agua",
                    "id": "1"
                }],
                "level": 5,
                "id": 59,
                "ataque": 4,
                "defesa": 1,
                "vida": 44
            }, {
                "icone": "./spas/resources/icones/61.png",
                "nome": "Poliwhirl",
                "tipos": [{
                    "nome": "agua",
                    "id": "1"
                }],
                "level": 5,
                "id": 60,
                "ataque": 12,
                "defesa": 3,
                "vida": 95
            }, {
                "icone": "./spas/resources/icones/62.png",
                "nome": "Poliwrath",
                "tipos": [{
                    "nome": "lutador",
                    "id": "1"
                }, {
                    "nome": "agua",
                    "id": "2"
                }],
                "level": 5,
                "id": 61,
                "ataque": 3,
                "defesa": 15,
                "vida": 82
            }, {
                "icone": "./spas/resources/icones/63.png",
                "nome": "Abra",
                "tipos": [{
                    "nome": "psiquico",
                    "id": "1"
                }],
                "level": 5,
                "id": 62,
                "ataque": 8,
                "defesa": 3,
                "vida": 96
            }, {
                "icone": "./spas/resources/icones/64.png",
                "nome": "Kadabra",
                "tipos": [{
                    "nome": "psiquico",
                    "id": "1"
                }],
                "level": 5,
                "id": 63,
                "ataque": 18,
                "defesa": 1,
                "vida": 94
            }, {
                "icone": "./spas/resources/icones/65.png",
                "nome": "Alakazam",
                "tipos": [{
                    "nome": "psiquico",
                    "id": "1"
                }],
                "level": 5,
                "id": 64,
                "ataque": 13,
                "defesa": 6,
                "vida": 53
            }, {
                "icone": "./spas/resources/icones/66.png",
                "nome": "Machop",
                "tipos": [{
                    "nome": "lutador",
                    "id": "1"
                }],
                "level": 5,
                "id": 65,
                "ataque": 14,
                "defesa": 4,
                "vida": 35
            }, {
                "icone": "./spas/resources/icones/67.png",
                "nome": "Machoke",
                "tipos": [{
                    "nome": "lutador",
                    "id": "1"
                }],
                "level": 5,
                "id": 66,
                "ataque": 18,
                "defesa": 19,
                "vida": 47
            }, {
                "icone": "./spas/resources/icones/68.png",
                "nome": "Machamp",
                "tipos": [{
                    "nome": "lutador",
                    "id": "1"
                }],
                "level": 5,
                "id": 67,
                "ataque": 8,
                "defesa": 4,
                "vida": 40
            }, {
                "icone": "./spas/resources/icones/69.png",
                "nome": "Bellsprout",
                "tipos": [{
                    "nome": "venenoso",
                    "id": "1"
                }, {
                    "nome": "grama",
                    "id": "2"
                }],
                "level": 5,
                "id": 68,
                "ataque": 9,
                "defesa": 15,
                "vida": 72
            }, {
                "icone": "./spas/resources/icones/70.png",
                "nome": "Weepinbell",
                "tipos": [{
                    "nome": "venenoso",
                    "id": "1"
                }, {
                    "nome": "grama",
                    "id": "2"
                }],
                "level": 5,
                "id": 69,
                "ataque": 3,
                "defesa": 5,
                "vida": 26
            }, {
                "icone": "./spas/resources/icones/71.png",
                "nome": "Victreebel",
                "tipos": [{
                    "nome": "venenoso",
                    "id": "1"
                }, {
                    "nome": "grama",
                    "id": "2"
                }],
                "level": 5,
                "id": 70,
                "ataque": 3,
                "defesa": 8,
                "vida": 33
            }, {
                "icone": "./spas/resources/icones/72.png",
                "nome": "Tentacool",
                "tipos": [{
                    "nome": "venenoso",
                    "id": "1"
                }, {
                    "nome": "agua",
                    "id": "2"
                }],
                "level": 5,
                "id": 71,
                "ataque": 19,
                "defesa": 5,
                "vida": 79
            }, {
                "icone": "./spas/resources/icones/73.png",
                "nome": "Tentacruel",
                "tipos": [{
                    "nome": "venenoso",
                    "id": "1"
                }, {
                    "nome": "agua",
                    "id": "2"
                }],
                "level": 5,
                "id": 72,
                "ataque": 13,
                "defesa": 7,
                "vida": 58
            }, {
                "icone": "./spas/resources/icones/74.png",
                "nome": "Geodude",
                "tipos": [{
                    "nome": "terrestre",
                    "id": "1"
                }, {
                    "nome": "pedra",
                    "id": "2"
                }],
                "level": 5,
                "id": 73,
                "ataque": 15,
                "defesa": 12,
                "vida": 34
            }, {
                "icone": "./spas/resources/icones/75.png",
                "nome": "Graveler",
                "tipos": [{
                    "nome": "terrestre",
                    "id": "1"
                }, {
                    "nome": "pedra",
                    "id": "2"
                }],
                "level": 5,
                "id": 74,
                "ataque": 5,
                "defesa": 2,
                "vida": 34
            }, {
                "icone": "./spas/resources/icones/76.png",
                "nome": "Golem",
                "tipos": [{
                    "nome": "terrestre",
                    "id": "1"
                }, {
                    "nome": "pedra",
                    "id": "2"
                }],
                "level": 5,
                "id": 75,
                "ataque": 10,
                "defesa": 15,
                "vida": 44
            }, {
                "icone": "./spas/resources/icones/77.png",
                "nome": "Ponyta",
                "tipos": [{
                    "nome": "fogo",
                    "id": "1"
                }],
                "level": 5,
                "id": 76,
                "ataque": 4,
                "defesa": 15,
                "vida": 73
            }, {
                "icone": "./spas/resources/icones/78.png",
                "nome": "Rapidash",
                "tipos": [{
                    "nome": "fogo",
                    "id": "1"
                }],
                "level": 5,
                "id": 77,
                "ataque": 8,
                "defesa": 15,
                "vida": 94
            }, {
                "icone": "./spas/resources/icones/79.png",
                "nome": "Slowpoke",
                "tipos": [{
                    "nome": "agua",
                    "id": "1"
                }, {
                    "nome": "psiquico",
                    "id": "2"
                }],
                "level": 5,
                "id": 78,
                "ataque": 17,
                "defesa": 16,
                "vida": 74
            }, {
                "icone": "./spas/resources/icones/80.png",
                "nome": "Slowbro",
                "tipos": [{
                    "nome": "agua",
                    "id": "1"
                }, {
                    "nome": "psiquico",
                    "id": "2"
                }],
                "level": 5,
                "id": 79,
                "ataque": 9,
                "defesa": 9,
                "vida": 48
            }, {
                "icone": "./spas/resources/icones/81.png",
                "nome": "Magnemite",
                "tipos": [{
                    "nome": "aco",
                    "id": "1"
                }, {
                    "nome": "eletrico",
                    "id": "2"
                }],
                "level": 5,
                "id": 80,
                "ataque": 4,
                "defesa": 8,
                "vida": 30
            }, {
                "icone": "./spas/resources/icones/82.png",
                "nome": "Magneton",
                "tipos": [{
                    "nome": "aco",
                    "id": "1"
                }, {
                    "nome": "eletrico",
                    "id": "2"
                }],
                "level": 5,
                "id": 81,
                "ataque": 19,
                "defesa": 6,
                "vida": 27
            }, {
                "icone": "./spas/resources/icones/83.png",
                "nome": "Farfetchd",
                "tipos": [{
                    "nome": "normal",
                    "id": "1"
                }, {
                    "nome": "voador",
                    "id": "2"
                }],
                "level": 5,
                "id": 82,
                "ataque": 1,
                "defesa": 11,
                "vida": 76
            }, {
                "icone": "./spas/resources/icones/84.png",
                "nome": "Doduo",
                "tipos": [{
                    "nome": "normal",
                    "id": "1"
                }, {
                    "nome": "voador",
                    "id": "2"
                }],
                "level": 5,
                "id": 83,
                "ataque": 18,
                "defesa": 10,
                "vida": 64
            }, {
                "icone": "./spas/resources/icones/85.png",
                "nome": "Dodrio",
                "tipos": [{
                    "nome": "normal",
                    "id": "1"
                }, {
                    "nome": "voador",
                    "id": "2"
                }],
                "level": 5,
                "id": 84,
                "ataque": 13,
                "defesa": 4,
                "vida": 93
            }, {
                "icone": "./spas/resources/icones/86.png",
                "nome": "Seel",
                "tipos": [{
                    "nome": "agua",
                    "id": "1"
                }],
                "level": 5,
                "id": 85,
                "ataque": 10,
                "defesa": 7,
                "vida": 59
            }, {
                "icone": "./spas/resources/icones/87.png",
                "nome": "Dewgong",
                "tipos": [{
                    "nome": "agua",
                    "id": "1"
                }, {
                    "nome": "gelo",
                    "id": "2"
                }],
                "level": 5,
                "id": 86,
                "ataque": 7,
                "defesa": 13,
                "vida": 42
            }, {
                "icone": "./spas/resources/icones/88.png",
                "nome": "Grimer",
                "tipos": [{
                    "nome": "venenoso",
                    "id": "1"
                }],
                "level": 5,
                "id": 87,
                "ataque": 2,
                "defesa": 6,
                "vida": 48
            }, {
                "icone": "./spas/resources/icones/89.png",
                "nome": "Muk",
                "tipos": [{
                    "nome": "venenoso",
                    "id": "1"
                }],
                "level": 5,
                "id": 88,
                "ataque": 10,
                "defesa": 10,
                "vida": 62
            }, {
                "icone": "./spas/resources/icones/90.png",
                "nome": "Shellder",
                "tipos": [{
                    "nome": "agua",
                    "id": "1"
                }],
                "level": 5,
                "id": 89,
                "ataque": 16,
                "defesa": 11,
                "vida": 93
            }, {
                "icone": "./spas/resources/icones/91.png",
                "nome": "Cloyster",
                "tipos": [{
                    "nome": "agua",
                    "id": "1"
                }, {
                    "nome": "gelo",
                    "id": "2"
                }],
                "level": 5,
                "id": 90,
                "ataque": 10,
                "defesa": 10,
                "vida": 26
            }, {
                "icone": "./spas/resources/icones/92.png",
                "nome": "Gastly",
                "tipos": [{
                    "nome": "venenoso",
                    "id": "1"
                }, {
                    "nome": "fantasma",
                    "id": "2"
                }],
                "level": 5,
                "id": 91,
                "ataque": 3,
                "defesa": 6,
                "vida": 62
            }, {
                "icone": "./spas/resources/icones/93.png",
                "nome": "Haunter",
                "tipos": [{
                    "nome": "venenoso",
                    "id": "1"
                }, {
                    "nome": "fantasma",
                    "id": "2"
                }],
                "level": 5,
                "id": 92,
                "ataque": 5,
                "defesa": 16,
                "vida": 38
            }, {
                "icone": "./spas/resources/icones/94.png",
                "nome": "Gengar",
                "tipos": [{
                    "nome": "venenoso",
                    "id": "1"
                }, {
                    "nome": "fantasma",
                    "id": "2"
                }],
                "level": 5,
                "id": 93,
                "ataque": 1,
                "defesa": 11,
                "vida": 33
            }, {
                "icone": "./spas/resources/icones/95.png",
                "nome": "Onix",
                "tipos": [{
                    "nome": "terrestre",
                    "id": "1"
                }, {
                    "nome": "pedra",
                    "id": "2"
                }],
                "level": 5,
                "id": 94,
                "ataque": 16,
                "defesa": 1,
                "vida": 20
            }, {
                "icone": "./spas/resources/icones/96.png",
                "nome": "Drowzee",
                "tipos": [{
                    "nome": "psiquico",
                    "id": "1"
                }],
                "level": 5,
                "id": 95,
                "ataque": 6,
                "defesa": 2,
                "vida": 70
            }, {
                "icone": "./spas/resources/icones/97.png",
                "nome": "Hypno",
                "tipos": [{
                    "nome": "psiquico",
                    "id": "1"
                }],
                "level": 5,
                "id": 96,
                "ataque": 14,
                "defesa": 14,
                "vida": 93
            }, {
                "icone": "./spas/resources/icones/98.png",
                "nome": "Krabby",
                "tipos": [{
                    "nome": "agua",
                    "id": "1"
                }],
                "level": 5,
                "id": 97,
                "ataque": 8,
                "defesa": 11,
                "vida": 60
            }, {
                "icone": "./spas/resources/icones/99.png",
                "nome": "Kingler",
                "tipos": [{
                    "nome": "agua",
                    "id": "1"
                }],
                "level": 5,
                "id": 98,
                "ataque": 11,
                "defesa": 5,
                "vida": 22
            }, {
                "icone": "./spas/resources/icones/100.png",
                "nome": "Voltorb",
                "tipos": [{
                    "nome": "eletrico",
                    "id": "1"
                }],
                "level": 5,
                "id": 99,
                "ataque": 18,
                "defesa": 8,
                "vida": 66
            }, {
                "icone": "./spas/resources/icones/101.png",
                "nome": "Electrode",
                "tipos": [{
                    "nome": "eletrico",
                    "id": "1"
                }],
                "level": 5,
                "id": 100,
                "ataque": 6,
                "defesa": 13,
                "vida": 22
            }, {
                "icone": "./spas/resources/icones/102.png",
                "nome": "Exeggcute",
                "tipos": [{
                    "nome": "grama",
                    "id": "1"
                }, {
                    "nome": "psiquico",
                    "id": "2"
                }],
                "level": 5,
                "id": 101,
                "ataque": 15,
                "defesa": 1,
                "vida": 33
            }, {
                "icone": "./spas/resources/icones/103.png",
                "nome": "Exeggutor",
                "tipos": [{
                    "nome": "grama",
                    "id": "1"
                }, {
                    "nome": "psiquico",
                    "id": "2"
                }],
                "level": 5,
                "id": 102,
                "ataque": 8,
                "defesa": 15,
                "vida": 64
            }, {
                "icone": "./spas/resources/icones/104.png",
                "nome": "Cubone",
                "tipos": [{
                    "nome": "terrestre",
                    "id": "1"
                }],
                "level": 5,
                "id": 103,
                "ataque": 13,
                "defesa": 15,
                "vida": 34
            }, {
                "icone": "./spas/resources/icones/105.png",
                "nome": "Marowak",
                "tipos": [{
                    "nome": "terrestre",
                    "id": "1"
                }],
                "level": 5,
                "id": 104,
                "ataque": 8,
                "defesa": 5,
                "vida": 21
            }, {
                "icone": "./spas/resources/icones/106.png",
                "nome": "Hitmonlee",
                "tipos": [{
                    "nome": "lutador",
                    "id": "1"
                }],
                "level": 5,
                "id": 105,
                "ataque": 13,
                "defesa": 4,
                "vida": 89
            }, {
                "icone": "./spas/resources/icones/107.png",
                "nome": "Hitmonchan",
                "tipos": [{
                    "nome": "lutador",
                    "id": "1"
                }],
                "level": 5,
                "id": 106,
                "ataque": 3,
                "defesa": 9,
                "vida": 69
            }, {
                "icone": "./spas/resources/icones/108.png",
                "nome": "Lickitung",
                "tipos": [{
                    "nome": "normal",
                    "id": "1"
                }],
                "level": 5,
                "id": 107,
                "ataque": 16,
                "defesa": 13,
                "vida": 88
            }, {
                "icone": "./spas/resources/icones/109.png",
                "nome": "Koffing",
                "tipos": [{
                    "nome": "venenoso",
                    "id": "1"
                }],
                "level": 5,
                "id": 108,
                "ataque": 14,
                "defesa": 3,
                "vida": 88
            }, {
                "icone": "./spas/resources/icones/110.png",
                "nome": "Weezing",
                "tipos": [{
                    "nome": "venenoso",
                    "id": "1"
                }],
                "level": 5,
                "id": 109,
                "ataque": 6,
                "defesa": 10,
                "vida": 28
            }, {
                "icone": "./spas/resources/icones/111.png",
                "nome": "Rhyhorn",
                "tipos": [{
                    "nome": "terrestre",
                    "id": "1"
                }, {
                    "nome": "pedra",
                    "id": "2"
                }],
                "level": 5,
                "id": 110,
                "ataque": 5,
                "defesa": 17,
                "vida": 27
            }, {
                "icone": "./spas/resources/icones/112.png",
                "nome": "Rhydon",
                "tipos": [{
                    "nome": "terrestre",
                    "id": "1"
                }, {
                    "nome": "pedra",
                    "id": "2"
                }],
                "level": 5,
                "id": 111,
                "ataque": 11,
                "defesa": 16,
                "vida": 71
            }, {
                "icone": "./spas/resources/icones/113.png",
                "nome": "Chansey",
                "tipos": [{
                    "nome": "normal",
                    "id": "1"
                }],
                "level": 5,
                "id": 112,
                "ataque": 6,
                "defesa": 17,
                "vida": 23
            }, {
                "icone": "./spas/resources/icones/114.png",
                "nome": "Tangela",
                "tipos": [{
                    "nome": "grama",
                    "id": "1"
                }],
                "level": 5,
                "id": 113,
                "ataque": 1,
                "defesa": 6,
                "vida": 49
            }, {
                "icone": "./spas/resources/icones/115.png",
                "nome": "Kangaskhan",
                "tipos": [{
                    "nome": "normal",
                    "id": "1"
                }],
                "level": 5,
                "id": 114,
                "ataque": 15,
                "defesa": 12,
                "vida": 54
            }, {
                "icone": "./spas/resources/icones/116.png",
                "nome": "Horsea",
                "tipos": [{
                    "nome": "agua",
                    "id": "1"
                }],
                "level": 5,
                "id": 115,
                "ataque": 7,
                "defesa": 15,
                "vida": 86
            }, {
                "icone": "./spas/resources/icones/117.png",
                "nome": "Seadra",
                "tipos": [{
                    "nome": "agua",
                    "id": "1"
                }],
                "level": 5,
                "id": 116,
                "ataque": 12,
                "defesa": 1,
                "vida": 59
            }, {
                "icone": "./spas/resources/icones/118.png",
                "nome": "Goldeen",
                "tipos": [{
                    "nome": "agua",
                    "id": "1"
                }],
                "level": 5,
                "id": 117,
                "ataque": 10,
                "defesa": 6,
                "vida": 22
            }, {
                "icone": "./spas/resources/icones/119.png",
                "nome": "Seaking",
                "tipos": [{
                    "nome": "agua",
                    "id": "1"
                }],
                "level": 5,
                "id": 118,
                "ataque": 15,
                "defesa": 18,
                "vida": 79
            }, {
                "icone": "./spas/resources/icones/120.png",
                "nome": "Staryu",
                "tipos": [{
                    "nome": "agua",
                    "id": "1"
                }],
                "level": 5,
                "id": 119,
                "ataque": 12,
                "defesa": 14,
                "vida": 22
            }, {
                "icone": "./spas/resources/icones/121.png",
                "nome": "Starmie",
                "tipos": [{
                    "nome": "agua",
                    "id": "1"
                }, {
                    "nome": "psiquico",
                    "id": "2"
                }],
                "level": 5,
                "id": 120,
                "ataque": 3,
                "defesa": 19,
                "vida": 39
            }, {
                "icone": "./spas/resources/icones/122.png",
                "nome": "Mr-mime",
                "tipos": [{
                    "nome": "fada",
                    "id": "1"
                }, {
                    "nome": "psiquico",
                    "id": "2"
                }],
                "level": 5,
                "id": 121,
                "ataque": 14,
                "defesa": 5,
                "vida": 43
            }, {
                "icone": "./spas/resources/icones/123.png",
                "nome": "Scyther",
                "tipos": [{
                    "nome": "voador",
                    "id": "1"
                }, {
                    "nome": "inseto",
                    "id": "2"
                }],
                "level": 5,
                "id": 122,
                "ataque": 16,
                "defesa": 8,
                "vida": 80
            }, {
                "icone": "./spas/resources/icones/124.png",
                "nome": "Jynx",
                "tipos": [{
                    "nome": "gelo",
                    "id": "1"
                }, {
                    "nome": "psiquico",
                    "id": "2"
                }],
                "level": 5,
                "id": 123,
                "ataque": 5,
                "defesa": 6,
                "vida": 62
            }, {
                "icone": "./spas/resources/icones/125.png",
                "nome": "Electabuzz",
                "tipos": [{
                    "nome": "eletrico",
                    "id": "1"
                }],
                "level": 5,
                "id": 124,
                "ataque": 1,
                "defesa": 2,
                "vida": 21
            }, {
                "icone": "./spas/resources/icones/126.png",
                "nome": "Magmar",
                "tipos": [{
                    "nome": "fogo",
                    "id": "1"
                }],
                "level": 5,
                "id": 125,
                "ataque": 18,
                "defesa": 16,
                "vida": 39
            }, {
                "icone": "./spas/resources/icones/127.png",
                "nome": "Pinsir",
                "tipos": [{
                    "nome": "inseto",
                    "id": "1"
                }],
                "level": 5,
                "id": 126,
                "ataque": 17,
                "defesa": 10,
                "vida": 97
            }, {
                "icone": "./spas/resources/icones/128.png",
                "nome": "Tauros",
                "tipos": [{
                    "nome": "normal",
                    "id": "1"
                }],
                "level": 5,
                "id": 127,
                "ataque": 16,
                "defesa": 8,
                "vida": 76
            }, {
                "icone": "./spas/resources/icones/129.png",
                "nome": "Magikarp",
                "tipos": [{
                    "nome": "agua",
                    "id": "1"
                }],
                "level": 5,
                "id": 128,
                "ataque": 4,
                "defesa": 9,
                "vida": 53
            }, {
                "icone": "./spas/resources/icones/130.png",
                "nome": "Gyarados",
                "tipos": [{
                    "nome": "voador",
                    "id": "1"
                }, {
                    "nome": "agua",
                    "id": "2"
                }],
                "level": 5,
                "id": 129,
                "ataque": 1,
                "defesa": 9,
                "vida": 38
            }, {
                "icone": "./spas/resources/icones/131.png",
                "nome": "Lapras",
                "tipos": [{
                    "nome": "agua",
                    "id": "1"
                }, {
                    "nome": "gelo",
                    "id": "2"
                }],
                "level": 5,
                "id": 130,
                "ataque": 9,
                "defesa": 10,
                "vida": 42
            }, {
                "icone": "./spas/resources/icones/132.png",
                "nome": "Ditto",
                "tipos": [{
                    "nome": "normal",
                    "id": "1"
                }],
                "level": 5,
                "id": 131,
                "ataque": 10,
                "defesa": 14,
                "vida": 87
            }, {
                "icone": "./spas/resources/icones/133.png",
                "nome": "Eevee",
                "tipos": [{
                    "nome": "normal",
                    "id": "1"
                }],
                "level": 5,
                "id": 132,
                "ataque": 5,
                "defesa": 6,
                "vida": 80
            }, {
                "icone": "./spas/resources/icones/134.png",
                "nome": "Vaporeon",
                "tipos": [{
                    "nome": "agua",
                    "id": "1"
                }],
                "level": 5,
                "id": 133,
                "ataque": 11,
                "defesa": 14,
                "vida": 48
            }, {
                "icone": "./spas/resources/icones/135.png",
                "nome": "Jolteon",
                "tipos": [{
                    "nome": "eletrico",
                    "id": "1"
                }],
                "level": 5,
                "id": 134,
                "ataque": 8,
                "defesa": 17,
                "vida": 40
            }, {
                "icone": "./spas/resources/icones/136.png",
                "nome": "Flareon",
                "tipos": [{
                    "nome": "fogo",
                    "id": "1"
                }],
                "level": 5,
                "id": 135,
                "ataque": 12,
                "defesa": 4,
                "vida": 80
            }, {
                "icone": "./spas/resources/icones/137.png",
                "nome": "Porygon",
                "tipos": [{
                    "nome": "normal",
                    "id": "1"
                }],
                "level": 5,
                "id": 136,
                "ataque": 2,
                "defesa": 3,
                "vida": 67
            }, {
                "icone": "./spas/resources/icones/138.png",
                "nome": "Omanyte",
                "tipos": [{
                    "nome": "pedra",
                    "id": "1"
                }, {
                    "nome": "agua",
                    "id": "2"
                }],
                "level": 5,
                "id": 137,
                "ataque": 8,
                "defesa": 18,
                "vida": 50
            }, {
                "icone": "./spas/resources/icones/139.png",
                "nome": "Omastar",
                "tipos": [{
                    "nome": "pedra",
                    "id": "1"
                }, {
                    "nome": "agua",
                    "id": "2"
                }],
                "level": 5,
                "id": 138,
                "ataque": 13,
                "defesa": 18,
                "vida": 58
            }, {
                "icone": "./spas/resources/icones/140.png",
                "nome": "Kabuto",
                "tipos": [{
                    "nome": "pedra",
                    "id": "1"
                }, {
                    "nome": "agua",
                    "id": "2"
                }],
                "level": 5,
                "id": 139,
                "ataque": 8,
                "defesa": 12,
                "vida": 21
            }, {
                "icone": "./spas/resources/icones/141.png",
                "nome": "Kabutops",
                "tipos": [{
                    "nome": "pedra",
                    "id": "1"
                }, {
                    "nome": "agua",
                    "id": "2"
                }],
                "level": 5,
                "id": 140,
                "ataque": 1,
                "defesa": 18,
                "vida": 94
            }, {
                "icone": "./spas/resources/icones/142.png",
                "nome": "Aerodactyl",
                "tipos": [{
                    "nome": "voador",
                    "id": "1"
                }, {
                    "nome": "pedra",
                    "id": "2"
                }],
                "level": 5,
                "id": 141,
                "ataque": 14,
                "defesa": 5,
                "vida": 27
            }, {
                "icone": "./spas/resources/icones/143.png",
                "nome": "Snorlax",
                "tipos": [{
                    "nome": "normal",
                    "id": "1"
                }],
                "level": 5,
                "id": 142,
                "ataque": 4,
                "defesa": 9,
                "vida": 21
            }, {
                "icone": "./spas/resources/icones/144.png",
                "nome": "Articuno",
                "tipos": [{
                    "nome": "voador",
                    "id": "1"
                }, {
                    "nome": "gelo",
                    "id": "2"
                }],
                "level": 5,
                "id": 143,
                "ataque": 1,
                "defesa": 15,
                "vida": 96
            }, {
                "icone": "./spas/resources/icones/145.png",
                "nome": "Zapdos",
                "tipos": [{
                    "nome": "voador",
                    "id": "1"
                }, {
                    "nome": "eletrico",
                    "id": "2"
                }],
                "level": 5,
                "id": 144,
                "ataque": 15,
                "defesa": 15,
                "vida": 45
            }, {
                "icone": "./spas/resources/icones/146.png",
                "nome": "Moltres",
                "tipos": [{
                    "nome": "voador",
                    "id": "1"
                }, {
                    "nome": "fogo",
                    "id": "2"
                }],
                "level": 5,
                "id": 145,
                "ataque": 11,
                "defesa": 2,
                "vida": 86
            }, {
                "icone": "./spas/resources/icones/147.png",
                "nome": "Dratini",
                "tipos": [{
                    "nome": "dragao",
                    "id": "1"
                }],
                "level": 5,
                "id": 146,
                "ataque": 9,
                "defesa": 7,
                "vida": 48
            }, {
                "icone": "./spas/resources/icones/148.png",
                "nome": "Dragaonair",
                "tipos": [{
                    "nome": "dragao",
                    "id": "1"
                }],
                "level": 5,
                "id": 147,
                "ataque": 18,
                "defesa": 19,
                "vida": 54
            }, {
                "icone": "./spas/resources/icones/149.png",
                "nome": "Dragonite",
                "tipos": [{
                    "nome": "voador",
                    "id": "1"
                }, {
                    "nome": "dragao",
                    "id": "2"
                }],
                "level": 5,
                "id": 148,
                "ataque": 3,
                "defesa": 2,
                "vida": 73
            }, {
                "icone": "./spas/resources/icones/150.png",
                "nome": "Mewtwo",
                "tipos": [{
                    "nome": "psiquico",
                    "id": "1"
                }],
                "level": 5,
                "id": 149,
                "ataque": 16,
                "defesa": 1,
                "vida": 83
            }, {
                "icone": "./spas/resources/icones/151.png",
                "nome": "Mew",
                "tipos": [{
                    "nome": "psiquico",
                    "id": "1"
                }],
                "level": 5,
                "id": 150,
                "ataque": 10,
                "defesa": 14,
                "vida": 56
            }];
            return obj;
        };
    }
})(angular);